version: '3.2'
services:
  elasticsearch:
    image: ssamd-elasticsearch-with-nori
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
      discovery.type: single-node
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
    platform: linux/amd64
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    platform: linux/amd64

volumes:
  elasticsearch:
    driver: local

networks:
  elk:
    driver: bridge
